2023-11-16 22:46:13,177 INFO    MainThread:3229 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-11-16 22:46:13,178 INFO    MainThread:3229 [wandb_setup.py:_flush():76] Configure stats pid to 3229
2023-11-16 22:46:13,178 INFO    MainThread:3229 [wandb_setup.py:_flush():76] Loading settings from /home/inho/.config/wandb/settings
2023-11-16 22:46:13,178 INFO    MainThread:3229 [wandb_setup.py:_flush():76] Loading settings from /home/inho/df_detection/experiments_OC/wandb/settings
2023-11-16 22:46:13,178 INFO    MainThread:3229 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-16 22:46:13,178 INFO    MainThread:3229 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-16 22:46:13,178 INFO    MainThread:3229 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main_fusion.py', 'program_abspath': '/home/inho/df_detection/experiments_OC/main_fusion.py', 'program': 'main_fusion.py'}
2023-11-16 22:46:13,178 INFO    MainThread:3229 [wandb_init.py:_log_setup():528] Logging user logs to /home/inho/df_detection/experiments_OC/wandb/run-20231116_224613-3sj453re/logs/debug.log
2023-11-16 22:46:13,178 INFO    MainThread:3229 [wandb_init.py:_log_setup():529] Logging internal logs to /home/inho/df_detection/experiments_OC/wandb/run-20231116_224613-3sj453re/logs/debug-internal.log
2023-11-16 22:46:13,179 INFO    MainThread:3229 [wandb_init.py:init():568] calling init triggers
2023-11-16 22:46:13,179 INFO    MainThread:3229 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {'SEED': 42, 'DATASET': {'datadir': '/home/inho/df_detection/experiments_xception/data/', 'dataname': 'dataset4', 'mode': 'train'}, 'OPTIMIZER': {'opt_name': 'Adam', 'lr': 0.001}, 'TRAINING': {'batch_size': 32, 'test_batch_size': 32, 'epochs': 20, 'log_interval': 100, 'use_scheduler': True, 'amp': 'True', 'consistency_rate': 1.0}, 'MODEL': {'pretrain_path': '/media/data2/jiwon/DeepfakeAD/recog_model.pt', 'pretrain_path2': '/home/inho/df_detection/experiments_OC/model/xception-43020ad28.pth', 'model_name': 'xception', 'pre_logits': 'False'}, 'RESULT': {'savedir': '/media/data1/inho/df_detection/experiments_OC/saved_model/final/'}, 'MODIFYING': 'False', 'EXP_NAME': 'xception_OC2-dataset4'}
2023-11-16 22:46:13,179 INFO    MainThread:3229 [wandb_init.py:init():618] starting backend
2023-11-16 22:46:13,179 INFO    MainThread:3229 [wandb_init.py:init():622] setting up manager
2023-11-16 22:46:13,184 INFO    MainThread:3229 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-11-16 22:46:13,186 INFO    MainThread:3229 [wandb_init.py:init():628] backend started and connected
2023-11-16 22:46:13,193 INFO    MainThread:3229 [wandb_init.py:init():720] updated telemetry
2023-11-16 22:46:13,196 INFO    MainThread:3229 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-11-16 22:46:13,807 INFO    MainThread:3229 [wandb_run.py:_on_init():2220] communicating current version
2023-11-16 22:46:13,875 INFO    MainThread:3229 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.16.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-11-16 22:46:13,875 INFO    MainThread:3229 [wandb_init.py:init():804] starting run threads in backend
2023-11-16 22:46:14,101 WARNING MainThread:3229 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/home/inho/anaconda3/envs/df_detection/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/inho/anaconda3/envs/df_detection/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 815, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/inho/anaconda3/envs/df_detection/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/inho/anaconda3/envs/df_detection/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/inho/anaconda3/envs/df_detection/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/inho/anaconda3/envs/df_detection/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/inho/anaconda3/envs/df_detection/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
