Traceback (most recent call last):
  File "main.py", line 105, in <module>
    run(cfg)
  File "main.py", line 88, in run
    device       = device)
TypeError: fit() got an unexpected keyword argument 'recorded_epoch'